"""add historical_snapshots table

Revision ID: 3587d61f0e41
Revises: d4e5f6a7b8c9
Create Date: 2026-03-15 16:12:27.319691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3587d61f0e41"
down_revision: Union[str, Sequence[str], None] = "d4e5f6a7b8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("price_usd", sa.Double(), nullable=False),
        sa.Column("market_cap_usd", sa.Double(), nullable=False),
        sa.Column("volume_usd", sa.Double(), nullable=False),
        sa.Column("circulating_supply", sa.Double(), nullable=True),
        sa.Column("total_supply", sa.Double(), nullable=True),
        sa.Column("categories", sa.Text(), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "snapshot_date", name="uq_hist_snapshot_symbol_date"),
    )
    op.create_index(
        op.f("ix_historical_snapshots_snapshot_date"),
        "historical_snapshots",
        ["snapshot_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_snapshots_symbol"), "historical_snapshots", ["symbol"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_historical_snapshots_symbol"), table_name="historical_snapshots")
    op.drop_index(op.f("ix_historical_snapshots_snapshot_date"), table_name="historical_snapshots")
    op.drop_table("historical_snapshots")
    # ### end Alembic commands ###
