"""initial schema

Revision ID: e10c91a4be38
Revises:
Create Date: 2026-03-12 20:52:57.804287

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e10c91a4be38"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("coingecko_id", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("coingecko_id"),
    )
    op.create_index(op.f("ix_tokens_symbol"), "tokens", ["symbol"], unique=True)
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "triggered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_token_id"), "alerts", ["token_id"], unique=False)
    op.create_index(op.f("ix_alerts_triggered_at"), "alerts", ["triggered_at"], unique=False)
    op.create_table(
        "dev_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("commits_30d", sa.Integer(), nullable=False),
        sa.Column("contributors", sa.Integer(), nullable=False),
        sa.Column("stars", sa.Integer(), nullable=False),
        sa.Column("forks", sa.Integer(), nullable=False),
        sa.Column("open_issues", sa.Integer(), nullable=False),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dev_activity_collected_at"), "dev_activity", ["collected_at"], unique=False
    )
    op.create_index(op.f("ix_dev_activity_token_id"), "dev_activity", ["token_id"], unique=False)
    op.create_table(
        "market_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("price_usd", sa.Float(), nullable=False),
        sa.Column("market_cap_usd", sa.Float(), nullable=True),
        sa.Column("volume_24h_usd", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("ath_usd", sa.Float(), nullable=True),
        sa.Column("circulating_supply", sa.Float(), nullable=True),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_data_collected_at"), "market_data", ["collected_at"], unique=False
    )
    op.create_index(op.f("ix_market_data_token_id"), "market_data", ["token_id"], unique=False)
    op.create_table(
        "signals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("signal_type", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signals_generated_at"), "signals", ["generated_at"], unique=False)
    op.create_index(op.f("ix_signals_token_id"), "signals", ["token_id"], unique=False)
    op.create_table(
        "social_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("reddit_subscribers", sa.Integer(), nullable=False),
        sa.Column("reddit_posts_24h", sa.Integer(), nullable=False),
        sa.Column("sentiment_score", sa.Float(), nullable=False),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_social_data_collected_at"), "social_data", ["collected_at"], unique=False
    )
    op.create_index(op.f("ix_social_data_token_id"), "social_data", ["token_id"], unique=False)
    op.create_table(
        "token_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("fundamental_score", sa.Float(), nullable=False),
        sa.Column("opportunity_score", sa.Float(), nullable=False),
        sa.Column(
            "scored_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_scores_scored_at"), "token_scores", ["scored_at"], unique=False)
    op.create_index(op.f("ix_token_scores_token_id"), "token_scores", ["token_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_scores_token_id"), table_name="token_scores")
    op.drop_index(op.f("ix_token_scores_scored_at"), table_name="token_scores")
    op.drop_table("token_scores")
    op.drop_index(op.f("ix_social_data_token_id"), table_name="social_data")
    op.drop_index(op.f("ix_social_data_collected_at"), table_name="social_data")
    op.drop_table("social_data")
    op.drop_index(op.f("ix_signals_token_id"), table_name="signals")
    op.drop_index(op.f("ix_signals_generated_at"), table_name="signals")
    op.drop_table("signals")
    op.drop_index(op.f("ix_market_data_token_id"), table_name="market_data")
    op.drop_index(op.f("ix_market_data_collected_at"), table_name="market_data")
    op.drop_table("market_data")
    op.drop_index(op.f("ix_dev_activity_token_id"), table_name="dev_activity")
    op.drop_index(op.f("ix_dev_activity_collected_at"), table_name="dev_activity")
    op.drop_table("dev_activity")
    op.drop_index(op.f("ix_alerts_triggered_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_token_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_tokens_symbol"), table_name="tokens")
    op.drop_table("tokens")
    # ### end Alembic commands ###
